# Install and configure the Live Helper Chat application on Centos 7.9
 
- name: Wordpress Setup
  hosts: localhost
  tasks:

# 1 - Update the system
  - name: Update the system
    yum:
      name: '*'
      state: latest
      update_cache: yes

# 2 - Install EPEL and Remi repositories
  - name: Install EPEL repository
    yum:
      name: "{{ item }}"
      state: present
    with_items:
     - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     - https://rpms.remirepo.net/enterprise/remi-release-7.rpm

# 3 - Install yum-utils     
  - name: Install yum-utils
    yum:
      name: yum-utils
      state: present

# 4 - Disable Remi PHP 
  - name: Disable remi-php*
    command: yum-config-manager --disable 'remi-php*'

# 5 - Enable Remi PHP 8.0
  - name: Enable remi-php80
    command: yum-config-manager --enable remi-php80

# 6 - Install PHP and dependencies
  - name: Install PHP and dependencies
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php-json
      - php-cli
      - php-gd
      - php-xml
      - php-common
      - php-pdo
      - php-pecl-zip
      - php-mysqlnd
      - php-mbstring
      - php
      - php-bcmath
      - php-phpiredis
      - php-imap
      - php-pecl-redis4
      - php-pecl-igbinary
      - php-geos
      - php-fpm
      - php-opcache
      - MySQL-python
      - git

# 7 - Install Nginx and screen
  - name: Install Nginx and screen
    yum:
      name: "{{ item }}"
      state: present
      enable: yes
    with_items:
      - nginx
      - screen

# 8 - Download MySQL repository RPM      
  - name: Download MySQL repository RPM
    get_url:
      url: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      dest: /tmp/mysql80-community-release-el7-3.noarch.rpm

# 9 - Install MySQL repository
  - name: Install MySQL repository
    yum:
      name: /tmp/mysql80-community-release-el7-3.noarch.rpm
      state: present

# 10 - Import MySQL GPG key
  - name: Import MySQL GPG key
    rpm_key:
      key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
      state: present

# 11 - Install MySQL server
  - name: Install MySQL server
    yum:
      name: mysql-community-server
      state: present
      enable: yes

# 12 - Start MySQL service
  - name: Start MySQL service
    service:
      name: mysqld
      state: started
      enabled: yes

# 13 - Disable Selinux
  - name: Disable Selinux
    selinux:
      state: disabled

# 14 - Generate a random password
  - name: Generate a random password
    shell: >-
          openssl rand -hex 14
    register: mysql_root_pass 

# 15 - Get the Temporary root password
  - name: Get the Temporary root password
    shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
    register: mysql_root_password

# 16 - Set the root password
  - name: root | set root password
    shell: >-
          mysqladmin -u root
          --password="{{mysql_root_password.stdout}}"
          password "{{mysql_root_pass.stdout}}"

# 17 - Create a .my.cnf file
  - name: Create a .my.cnf file
    file:
      path: /root/.my.cnf
      state: touch
      owner: root 
      group: root 
      mode: 0600

# 18 - Add .my.cnf
  - name: Add .my.cnf
    lineinfile: 
      path: /root/.my.cnf
      line: "{{ item }}"
    with_items:
      - "[client]"
      - user=root
      - password={{mysql_root_pass.stdout}}

# 19 - Reload privilege tables
  - name: Reload privilege tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

# 20 - Remove anonymous users
  - name: Remove anonymous users
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_pass.stdout }}"
      user: ''
      host_all: yes
      state: absent

# 21 - Disallow root login remotely
  - name: Disallow root login remotely
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_pass.stdout }}"
      user: root
      host: "'localhost', '127.0.0.1', '::1'"
      state: absent

# 22 - Remove test database and access to it
  - name: Remove test database and access to it
    mysql_db: 
      login_user: root
      login_password: "{{ mysql_root_pass.stdout }}"
      db: test
      state: absent
    register: remove_testdb

# 23 - Reload privilege tables again and change the password policy
  - name: Reload privilege tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
        - SET GLOBAL validate_password_policy=LOW;
        - FLUSH PRIVILEGES
    changed_when: False

# 24 - Create a database
  - name: Create a database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_pass.stdout }}"
      name: lhc
      state: present

 # 25 - Generate a random password for mysql user
  - name: Generate a random password
    shell: >-
          openssl rand -hex 14
    register: lhc_db_pass

# 26 - Create a user
  - name: Create a user
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_pass.stdout }}"
      name: lhc
      password: "{{ lhc_db_pass.stdout }}"
      priv: 'lhc.*:ALL'
      state: present

 # 27 - clone the Live Helper Chat application to /usr/local/src
  - name: clone the Live Helper Chat application to /usr/local/src
    git:
      repo: https://github.com/LiveHelperChat/livehelperchat.git
      dest: /usr/local/src/livehelperchat

# 27.1 - Remove index.html from /var/www/html
  - name: Remove index.html from /var/www/html
    file:
      path: /var/www/html/index.html
      state: absent

# 28 - Move the content from /usr/local/src/livehelperchat/lhc_web to /var/www/html
  - name: Move the content from /usr/local/src/livehelperchat/lhc_web to /var/www/html
    shell: mv /usr/local/src/livehelperchat/lhc_web/* /var/www/html     

# 29 - Update the 777 permission for the following directoy's
  - name: Set directory permissions
    command: chmod -R 777 "{{ item.path }}"
    with_items:
      - { path: '/var/www/html/settings/' }
      - { path: '/var/www/html/var/storage' }
      - { path: '/var/www/html/var/userphoto' }
      - { path: '/var/www/html/var/storageform' }
      - { path: '/var/www/html/var/storageadmintheme' }
      - { path: '/var/www/html/var/botphoto' }
      - { path: '/var/www/html/var/bottrphoto' }
      - { path: '/var/www/html/var/storageinvitation' }
      - { path: '/var/www/html/var/storagedocshare' }
      - { path: '/var/www/html/var/storagetheme' }
      - { path: '/var/www/html/var/tmpfiles' }

# 30 - Move /var/www/html/cli/install-cli.php to /var/www/html
  - name: Move /var/www/html/cli/install-cli.php to /var/www/html
    shell: mv /var/www/html/cli/install-cli.php /var/www/html

# 31 - Move /var/www/html/cli/example.settings.ini to /var/www/html/settings.ini
  - name: Move /var/www/html/cli/example.settings.ini to /var/www/html/settings.ini
    shell: mv /var/www/html/cli/example.settings.ini /var/www/html/settings.ini

# 32 - Update the mysql details in the /var/www/html/settings.ini
  - name: Update database details in configuration file
    lineinfile:
      path: /var/www/html/settings.ini
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: '^host = .*', line: 'host = localhost' }
      - { regexp: '^user = .*', line: 'user = lhc' }
      - { regexp: '^password = .*', line: 'password = "{{ lhc_db_pass.stdout }}"'}
      - { regexp: '^database = .*', line: 'database = lhc' }
      - { regexp: '^port = .*', line: 'port = 3306' }

# 33 - Set up the Node.js repository for version 14.x on the system
  - name: Set up the Node.js repository for version 14.x on the system
    shell: curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -

# 34 - Install Node.js, npm and Redis
  - name: Install Node.js
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - nodejs
      - npm
      - redis

# 35 - Start Redis service
  - name: Start Redis service
    service:
      name: redis
      state: started
      enabled: yes

# 36 - Clone the LiveHelperChat/NodeJS-Helper from git to /usr/local/src
  - name: Clone the LiveHelperChat/NodeJS-Helper from git to /usr/local/src
    git:
      repo: https://github.com/LiveHelperChat/NodeJS-Helper.git
      dest: /usr/local/src/NodeJS-Helper

# 37 - Move the content from /usr/local/src/NodeJS-Helper to /var/www/html/extension
  - name: Move the content from /usr/local/src/NodeJS-Helper to /var/www/html/extension
    shell: mv /usr/local/src/NodeJS-Helper/* /var/www/html/extension/    

# 38 - Install composer dependencies from /var/www/html/extension/nodejshelper
  - name: Install composer dependencies from /var/www/html/extension/nodejshelper
    shell: composer install
    args:
      chdir: /var/www/html/extension/nodejshelper

# 39 - Install npm dependencies from /var/www/html/extension/nodejshelper/serversc/lhc
  - name: Install npm dependencies from /var/www/html/extension/nodejshelper/serversc/lhc
    shell: npm install
    args:
      chdir: /var/www/html/extension/nodejshelper/serversc/lhc

  # 40 - Copy the secret hash from /var/www/html/settings/settings.ini.php 
  - name: Retrieve secret hash from settings.ini.php
    shell: grep "secrethash" /var/www/html/settings/settings.ini.php  | cut -d "'" -f 4
    register: secret_hash_result

# 41 - Update secret hash in server.js
  - name: Update secret hash in server.js
    replace:
      path: /var/www/html/extension/nodejshelper/serversc/lhc/server.js
      regexp: "secretHash: '<use_your_secret_hash>'"
      replace: "secretHash: '{{ secret_hash_result.stdout }}'"
      backup: yes

# 42 - Make a copy make copy of /var/www/html/extension/nodejshelper/settings/settings.ini.default.php to /var/www/html/extension/nodejshelper/settings/settings.ini.default.php
  - name: Make a copy of settings.ini.default.php
    copy:
      src: /var/www/html/extension/nodejshelper/settings/settings.ini.default.php
      dest: /var/www/html/extension/nodejshelper/settings/settings.ini.php

# 43 - Clone the LiveHelperChat/lhc-php-resque to /usr/local/src
  - name: Clone the LiveHelperChat/lhc-php-resque to /usr/local/src
    git:
      repo: https://github.com/LiveHelperChat/lhc-php-resque.git
      dest: /usr/local/src/lhc-php-resque

# 44 - Move the directory from /usr/local/src/lhc-php-resque/lhcphpresque to /var/www/html/extension/
  - name: Move the directory from /usr/local/src/lhc-php-resque/lhcphpresque to /var/www/html/extension/
    shell: mv /usr/local/src/lhc-php-resque/lhcphpresque /var/www/html/extension/

# 45 - copy the nginx configuration jinja2 template from /opt/live-helper/Workout/livehelperchat.conf.j2 to /etc/nginx/conf.d
  - name: copy the nginx configuration jinja2 template
    template:
      src:  /opt/live-helper/Workout/livehelperchat.conf.j2
      dest: /etc/nginx/conf.d/livehelperchat.conf
      owner: root
      group: root
      mode: 0644
      remote_src: yes

# 46 - Copy the resque.php from /var/www/html/extension/lhcphpresque/doc/resque.php to  /var/www/html/
  - name: Copy the resque.php
    copy:
      src: /var/www/html/extension/lhcphpresque/doc/resque.php
      dest: /var/www/html/
      follow: yes

# 47 - Install composer dependencies from /var/www/html/extension/lhcphpresque
  - name: Install composer dependencies from /var/www/html/extension/lhcphpresque
    shell: composer update
    args:
      chdir: /var/www/html/extension/lhcphpresque

# 48 - Add cron job for lhcphpresque at reboot
  - name: Add cron job for lhcphpresque at reboot
    cron:
      name: "Run lhcphpresque at reboot"
      special_time: reboot
      job: "cd /var/www/web/extension/lhcphpresque/doc/ && ./phpresque.sh >> /dev/null 2>&1"

# 49 - Add cron job to create runresque.lock
  - name: Add cron job to create runresque.lock
    cron:
      name: "Create runresque.lock"
      minute: "40"
      hour: "7"
      job: "/bin/touch /var/www/web/extension/lhcphpresque/doc/runresque.lock > /dev/null 2>&1"

# 50 - Add cron job for resque.sh
  - name: Add cron job for resque.sh
    cron:
      name: "Run resque.sh every minute"
      job: "cd /var/www/web/extension/lhcphpresque/doc && ./resque.sh >> /dev/null 2>&1"

# 51 - Add cron job for nodejshelper restart
  - name: Add cron job for nodejshelper restart
    cron:
      name: "Restart nodejshelper daily"
      minute: "1"
      hour: "1"
      job: "/usr/sbin/service nodejshelper restart > /dev/null 2>&1"

# 52 - restart Nginx
  - name: restart Nginx
    service:
      name: nginx
      state: restarted
            