# Install and conffigure Aapanel on ubuntu 20.04

- name: Aapanel Setup
  hosts: localhost
  tasks:
#1 - Disable ssh access and restart the ssh service
  - name: Restarting sshd
    shell: "sed -i 's/#Match User anoncvs/ForceCommand echo Please wait until the installation is completed..../g' /etc/ssh/sshd_config && systemctl restart sshd"

# 2 - Update the system
  - name: Updating Packages
    ansible.builtin.apt:
      update_cache: yes

  - name: Install necessary dependencies
    package:
      name: "{{ item }}"
      state: present
    loop:
      - wget
      - expect  # Install expect package for handling interactions
    when: ansible_pkg_mgr == 'apt'  # Adjust this condition for your package manager (e.g., yum for CentOS/RHEL)

  - name: Download aaPanel installer
    get_url:
      url: http://www.aapanel.com/script/install-ubuntu_6.0_en.sh
      dest: /usr/local/src/install-ubuntu_6.0_en.sh
      mode: '0755'
  - name: Download aaPanel installer
    get_url:
      url: http://www.aapanel.com/script/install-ubuntu_6.0_en.sh
      dest: /usr/local/src/install-ubuntu_6.0_en.sh
      mode: '0755'

  
  - name: Run aaPanel installer with expect script
    shell: expect /usr/local/src/Aapanel/install_aapanel.exp


# 5 - Write a bt default command  output to a file
  - name: Write a bt default command  output to a file
    shell: "bt default > /root/.bt"  



  # 46 - create a cloudstack directory
  - name: Creating a directory for shell script
    ansible.builtin.file:
      path: /opt/Aapanel
      state: directory         

 # 47 - copy the shell script from /opt/ to /opt/cloudstack     
  - name: Copy files for shell script
    copy:
      src: "{{ item.confsrc }}"
      dest: "{{ item.confdest }}"
      remote_src: yes   
    with_items: 
      - { confsrc: '/usr/local/src/Aapanel/Aapanel-cleanup.sh', confdest: '/opt/cloudstack/'}  

# 48 - Add the shell script to .bashrc
  - name: Adding a line for shell script
    lineinfile:
      path: /root/.bashrc
      line: "chmod +x /opt/cloudstack/Aapanel-cleanup.sh && /opt/cloudstack/Aapanel-cleanup.sh"
      state: present

 # 49 - Enable the ssh  acess and restart the sshd service   
  - name: Restarting sshd
    shell: "sed -i 's/ForceCommand echo Please wait until the installation is completed..../#Match User anoncvs/g' /etc/ssh/sshd_config && systemctl restart sshd"



  
